site_name: npcpy
site_url: https://npcpy.readthedocs.io/
repo_url: https://github.com/NPC-Worldwide/npcpy

theme:
  name: readthedocs
  features:
    - navigation.tabs
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true

plugins:
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          selection:
            members:
              - public
            filters:
              - "!^__init__$"  
          rendering:
            show_source: true
            show_root_heading: false
nav:
  - Home: index.md
  - Installation: installation.md
  - Using npcpy: npcpy.md
    - API:
      - Image: api/image.md
      - Data Loading: api/data.md
      - LLM Functions: api/llm_funcs.md
      - Generation: api/gen.md
      - NPC, Team, Jinx: api/npc_compiler.md
      - NPC Sys Env Helpers: api/npc_sysenv.md
      - Memory & Search: api/memory.md
      - OCR: api/ocr.md
      - Tools: api/tools.md
      - Serve: api/serve.md
